/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Subtitle = string;
export type Label = string;
/**
 * The unit of the values. e.g. °C or km/h
 */
export type Unit = string;
/**
 * The amount of gauge sections. Starting from the min value, ending with the max value.
 */
export type Sections = number[];
/**
 * Background color for each section. This Array is one shorter than the number of sections.
 */
export type SectionBackgroundColors = {
  [k: string]: unknown;
}[];
/**
 * Calculate the average over the given number of newest values. (If pivoted, then per each of the pivot dataseries.) If not specified then the latest value is shown without modification.
 */
export type AverageLatestValues = number;
export type Value = number;
/**
 * You can specify a column in the input data to autogenerate dataseries for each distinct entry in this column. E.g. if you have a table with columns [city, timestamp, temperature] and specify ''city'' as pivot column, then you will get a gauge for each city.
 */
export type PivotColumn = string;
/**
 * The data used to draw this data series.
 */
export type Data = {
  value: Value;
  pivot?: PivotColumn;
  [k: string]: unknown;
}[];
export type Gauges = {
  label: Label;
  valueColor?: ValueColor;
  unit?: Unit;
  sections?: Sections;
  backgroundColors?: SectionBackgroundColors;
  averageLatest?: AverageLatestValues;
  data?: Data;
  [k: string]: unknown;
}[];

export interface GaugeChartConfiguration {
  settings?: GlobalSettings;
  dataseries?: Gauges;
  [k: string]: unknown;
}
export interface GlobalSettings {
  title?: Title;
  subTitle?: Subtitle;
  [k: string]: unknown;
}
export interface ValueColor {
  [k: string]: unknown;
}
