/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Subtitle = string;
export type Label = string;
/**
 * The unit of the values. e.g. °C or km/h
 */
export type Unit = string;
/**
 * The number of decimal places to show in the value. If not specified, precision is 0.
 */
export type Decimals = number;
/**
 * Draw multiple Charts based on the split column of a data table.
 */
export type MultiChart = boolean;
/**
 * The value of the gauge
 */
export type Value = number;
/**
 * This should be an ISO String date like 2023-11-04T22:47:52.351152+00:00. Will only be used to detect data age of data.
 */
export type Timestamp = string;
export type Value1 = number;
/**
 * You can specify a table column to autogenerate dataseries for each distinct entry in this column. E.g. if you have a table with columns [city, timestamp, temperature] and specify ''city'' as split column, then you will get a gauge for each city.
 */
export type SplitDataBy = string;
/**
 * Provide a list of values. Only the latest value is shown in the gauge unless you configure "Advanced Settings" below or use split data.
 */
export type Data = {
    tsp?: Timestamp;
    value?: Value1;
    pivot?: SplitDataBy;
    [k: string]: unknown;
}[];
/**
 * The start value of the gauge. If not specified 0 is used.
 */
export type GaugeStartValue = number;
export type RightLimit = number;
/**
 * The right limits of the gauge sections and the color for that section.
 */
export type SectionRightLimits = {
    limit?: RightLimit;
    sectionColor?: SectionColor;
    [k: string]: unknown;
}[];
/**
 * Calculate the average over the given number of newest values. (If you use 'split by', then per each of the split dataseries.) If not specified then the latest value is shown without modification.
 */
export type AverageLatestValues = number;
/**
 * If you provide timestamp data, the delivered value is only shown in the gauge when the age of the data is not older than the given maximum Latency in seconds.
 */
export type MaximumLatencyInSeconds = number;
export type Gauges = {
    label?: Label;
    valueColor?: ValueColor;
    unit?: Unit;
    precision?: Decimals;
    multiChart?: MultiChart;
    value?: Value;
    data?: Data;
    sections?: GaugeColorSections;
    advanced?: AdvancedConfiguration;
    [k: string]: unknown;
}[];

export interface GaugeChartConfiguration {
    title?: Title;
    subTitle?: Subtitle;
    dataseries?: Gauges;
    [k: string]: unknown;
}
export interface ValueColor {
    [k: string]: unknown;
}
export interface GaugeColorSections {
    gaugeMinValue?: GaugeStartValue;
    sectionLimits?: SectionRightLimits;
    [k: string]: unknown;
}
export interface SectionColor {
    [k: string]: unknown;
}
export interface AdvancedConfiguration {
    averageLatest?: AverageLatestValues;
    maxLatency?: MaximumLatencyInSeconds;
    [k: string]: unknown;
}
